

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock  #/var/lib/mysql/mysql.sock
  host: localhost

development:
  <<: *default
  database: microposts3_development


test:
  <<: *default
  database: microposts3_test


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: microposts3_production
  username: microposts3
  password: <%= ENV['MICROPOSTS3_DATABASE_PASSWORD'] %>
